// <auto-generated />
namespace Gaming_Club.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Marketedit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Marketedit));
        
        string IMigrationMetadata.Id
        {
            get { return "202106121734229_Market-edit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
