// <auto-generated />
namespace Gaming_Club.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixforPhoneNumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixforPhoneNumber));
        
        string IMigrationMetadata.Id
        {
            get { return "202106182326385_Fix-for-Phone-Number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
